services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    environment:
    - TZ=${TZ:-Asia/Kuala_Lumpur}
    - TZ=Asia/Kuala_Lumpur
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 3000:3000/tcp
    - 853:853/tcp
    volumes:
    - ./work:/opt/adguardhome/work
    - ./conf:/opt/adguardhome/conf
    networks:
    - pwn20wnd-network
    - default
networks:
  pwn20wnd-network:
    external: true
