services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
    - ${STIRLING_PDF_PORT:-8087}:8080
    volumes:
    - ./extraConfigs:/configs
    - ./customFiles:/customFiles
    - ./logs:/logs
    env_file:
    - .env
    environment:
    - TZ=${TZ:-Asia/Kuala_Lumpur}
    - DOCKER_ENABLE_SECURITY=${DOCKER_ENABLE_SECURITY:-false}
    - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=${INSTALL_BOOK_AND_ADVANCED_HTML_OPS:-false}
    - LANGS=${LANGS:-eng}
    - SYSTEM_DEFAULTLOCALE=${SYSTEM_DEFAULTLOCALE:-en_US}
    - TZ=Asia/Kuala_Lumpur
    networks:
    - pwn20wnd-network
    - default
networks:
  pwn20wnd-network:
    external: true
